### ISSUE TITLE
"Fixes to prevent autoloading on master from failing" don't work

### ISSUE THREAD

**Issue by dhs-rec** [badgerious/puppet-windows-env#9] opened 2015-03-24 11:25 UTC
Hi,

running Puppet 3.7.4 as the master, I see messages like the following every now and then, even with v2.2.1:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/type/windows_env: Could not autoload puppet/provider/windows_env/windows_env: can't convert Symbol into String.
        Could not open library 'libUser32.so': libUser32.so: cannot open shared object file: No such file or directory on node <node name>

**Comment by badgerious** [comment] 2015-03-24 13:32
I'll look into this. A few questions occur to me:

1. Does this happen on all nodes with windows_env resources, or only some?
2. Has the puppet master been running continuously since upgrading to 2.2.1?
3. Does anything seem to precipitate the error, e.g. happens right after a puppet master restart or right after the node has downloaded the new version of windows_env ?

**Comment by dhs-rec** [comment] 2015-03-24 13:42
From my observation, I'd say part of 3). I see this mainly on AWS instances on which the agents run for the first time after they came up.

No, the master hasn't been restarted after upgrading to 2.2.1.

**Comment by dhs-rec** [comment] 2015-03-24 14:18
I did restart the master now, but it didn't change the situation.

**Comment by badgerious** [comment] 2015-03-27 13:45
I poked at this a bit, but can't reproduce unless I scribble out the checks for the microsoft_windows feature before loading the FFI stuff. If you can, could you:

1. Apply the below patch (`cd windows_env && patch -p0 < /path/to/patch.diff`)
2. Restart the puppet master
3. Kick off a run on some node with a windows_env resource
4. Cat the contents of `/tmp/puplog` on the master and paste them here?

The error message certainly suggests that the master is trying to load parts of the provider which are protected by Puppet.features.microsoft_windows, which seems rather odd to me.

```diff
diff --git lib/puppet/provider/windows_env/windows_env.rb lib/puppet/provider/windows_env/windows_env.rb
index 331e1ee..30615b4 100644
--- lib/puppet/provider/windows_env/windows_env.rb
+++ lib/puppet/provider/windows_env/windows_env.rb
@@ -2,6 +2,7 @@
 # if some of them are present, the others should be too. This check prevents errors from 
 # non Windows nodes that have had this module pluginsynced to them. 
 if Puppet.features.microsoft_windows?
+  File.exists?('/tmp') && File.open('/tmp/puplog', 'a') { |f| f.write("CP 5\n") }
   require 'puppet/util/windows/error'
   require 'puppet/util/windows/security'
   require 'win32/registry' 
@@ -37,9 +38,13 @@ if Puppet.version < '3.4.0'
   end 
 end 
 
+File.exists?('/tmp') && File.open('/tmp/puplog', 'a') { |f| f.write("CP 1\n") }
+
 Puppet::Type.type(:windows_env).provide(:windows_env) do
   desc "Manage Windows environment variables"
 
+  File.exists?('/tmp') && File.open('/tmp/puplog', 'a') { |f| f.write("CP 2\n") }
+
   confine :feature => :windows_env
   confine :osfamily => :windows
   defaultfor :osfamily => :windows
@@ -48,8 +53,11 @@ Puppet::Type.type(:windows_env).provide(:windows_env) do
   # load the provider even if FFI is absent so that the catalog can continue
   # (and hopefully install FFI).
   if Puppet.features.windows_env? && Puppet.features.microsoft_windows?
+    File.exists?('/tmp') && File.open('/tmp/puplog', 'a') { |f| f.write("CP 3: windows_env: #{Puppet.features.windows_env?} windows: #{Puppet.features.microsoft_windows? }\n") }
+    require 'ffi'
     module self::WinAPI
-      extend FFI::Library
+      extend ::FFI::Library
+      File.exists?('/tmp') && File.open('/tmp/puplog', 'a') { |f| f.write("CP 4\n") }
 
       ffi_convention :stdcall

```

**Comment by badgerious** [comment] 2015-03-30 13:15
Incidentally, if the hackish patch above is not palatable in a prod environment, this one ought to be sufficient to answer my question, and is slightly nicer:

```diff
diff --git lib/puppet/provider/windows_env/windows_env.rb lib/puppet/provider/windows_env/windows_env.rb
index 331e1ee..fa639a4 100644
--- lib/puppet/provider/windows_env/windows_env.rb
+++ lib/puppet/provider/windows_env/windows_env.rb
@@ -48,6 +48,10 @@ Puppet::Type.type(:windows_env).provide(:windows_env) do
   # load the provider even if FFI is absent so that the catalog can continue
   # (and hopefully install FFI).
   if Puppet.features.windows_env? && Puppet.features.microsoft_windows?
+    if /mswin|mingw/ !~ RUBY_PLATFORM
+      Puppet.notice("Puppet.features.microsoft_windows? is true on non-windows node")
+    end
+    require 'ffi'
     module self::WinAPI
       extend FFI::Library

```

**Comment by dhs-rec** [comment] 2015-03-30 13:25
Sorry, did not find a timeslot for testing your patch today. Will try to do it tomorrow.

**Comment by badgerious** [comment] 2015-04-30 03:28
Is this still a problem? Have you had a chance to try the patch?

**Comment by dhs-rec** [comment] 2015-05-04 06:36
No, sorry. Didn't find any time to test it. Anyway, I could remove usage of windows_env from all classes we use in our AWS setup.

**Comment by badgerious** [comment] 2015-05-04 12:18
OK then. I'll close this.

**Closed by badgerious** 2015-05-04 12:18 UTC
